language: php
sudo: false
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - php: "nightly"
    - name: "Php CS Fixer"
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "nightly"
    - name: "Php CS Fixer"
      php: "7.3"
      env:
      - PHP_CS_FIXER=1

env:
  - CLOSURE_VERSION: 20161024

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer update --no-interaction --prefer-source

before_script:
  - tests/dl-closure.sh

script:
  - PATH=vendor/bin:$PATH
  - composer validate
  - |
    if [ "$PHP_CS_FIXER" ]; then
      composer config --unset platform.php
      composer require --dev friendsofphp/php-cs-fixer:2.16
      php-cs-fixer fix --verbose --diff --dry-run --ansi
    fi
  - vendor/bin/phpunit --verbose

# vim:ts=2:sw=2:et
